// Generated by tools/esp_compress.py
#define ESP_BINARIES_COUNT (1)

// const esp32_zipfile_t NINA_W102_1_7_5

const esp32_zipfile_t NINA_W102_1_7_5 = {
    .name = "NINA_W102-1.7.5.bin.gz",
    .data = NULL,
    .compressed_len = 634996,
    .uncompressed_len = 1160192,
    .md5 =
        {
            0x07,
            0x7c,
            0xec,
            0x6d,
            0xaa,
            0x68,
            0x13,
            0xc5,
            0xa4,
            0x68,
            0x0f,
            0x45,
            0xc9,
            0xd8,
            0x77,
            0x6b,
        },
};
