name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arduino-platform:
           - 'main_platforms'
           # for rp2040 brain
           - 'pico_rp2040_tinyusb'

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - uses: actions/checkout@v3

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0

    - uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r .

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}

    - name: doxygen
      env:
        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        PRETTYNAME : "Adafruit MSA301 Sensor Library"
      run: bash ci/doxy_gen_and_deploy.sh
